# Site wide configuration

title:            Rahul Patil's Personal Website!
locale:           en_US
url:              rahulpat13.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Rahul Patil
  avatar: bio-photo.jpg
  bio: "Graduate student at UNC Charlotte.Embedded Systems and Robotics Geek. Likes to Play Chess and Paint when free."
  email: rahulpat13@ieee.org
  disqus-shortname:
  twitter: rahulpat13
  facebook: rahul.patil1
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: rahulpat13
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: rahulpat13
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
